// CalorieTrack — transparent Scriptable widget for daily food tracking
// Shows today's calories + protein / carbs / fat from your Google Sheet.
//
// SETUP (same as SpendToday):
//  1) In Google Sheets, publish the tab that logs your food (File -> Share ->
//     "Publish to web" -> pick the tab -> "Comma-separated values (.csv)" ->
//     Publish) and paste the URL into CSV_URL below.
//  2) Save this file into "iCloud Drive/Scriptable".
//  3) Add a Scriptable widget -> choose "CalorieTrack". Optional Parameter =
//     position for transparency ("top"/"middle"/"bottom", small: "top-left"...).
//  4) Transparency reuses the transparent-*.png files generated by SpendToday_BG.
//
// Expected columns (auto-detected by header name; set fallbacks if needed):
//   date (dato/date/dag/transaction_date), kcal (kcal/kalorier/energy),
//   protein, carbs (kulhydrat/karbohydrat), fat (fedt), optional description.

// ---------- CONFIG ----------
const CSV_URL = "PASTE_YOUR_PUBLISHED_CSV_URL_HERE"; // e.g. .../spreadsheets/d/e/2PACX-.../pub?gid=0&single=true&output=csv
const HAS_HEADER = true;
const DATE_DDMM = true;            // Danish dd/mm dates; ISO yyyy-mm-dd also supported
const REFRESH_MINUTES = 15;        // widget refresh cadence (iOS decides the exact time)
const TRANSPARENT = true;
const FALLBACK = { date: 0, kcal: 1, protein: 2, carbs: 3, fat: 4 };
// ---------- END CONFIG ----------

const WEEKDAYS = ["søndag", "mandag", "tirsdag", "onsdag", "torsdag", "fredag", "lørdag"];
const MONTHS = ["januar", "februar", "marts", "april", "maj", "juni", "juli", "august", "september", "oktober", "november", "december"];
const ACCENT_C = new Color("#fb923c");   // warm orange — food accent
const MAIN_C = new Color("#ffffff");
const MUTED_C = new Color("#9ca3af");
const P_C = new Color("#f87171");        // protein — red
const C_C = new Color("#fbbf24");        // carbs — amber
const F_C = new Color("#60a5fa");        // fat — blue

function scriptDir() {
  const fm = FileManager.iCloud();
  const p = module.filename;
  return p ? p.replace(/[^/]*$/, "") : fm.documentsDirectory();
}

async function loadCsv() {
  const req = new Request(CSV_URL);
  req.timeoutInterval = 15;
  const text = await req.loadString();
  if (!text || text.length < 50 && !text.includes(",")) throw new Error("Tomt svar fra regnearket");
  return text;
}

function csvToRows(text) {
  const rows = []; let row = [], cur = "", q = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (q) {
      if (c === '"') { if (text[i + 1] === '"') { cur += '"'; i++; } else q = false; }
      else cur += c;
    } else if (c === '"') q = true;
    else if (c === ",") { row.push(cur); cur = ""; }
    else if (c === "\n") { row.push(cur); rows.push(row); row = []; cur = ""; }
    else if (c !== "\r") cur += c;
  }
  if (cur.length || row.length) { row.push(cur); rows.push(row); }
  return rows.filter(r => r.some(c => String(c).trim() !== ""));
}

function parseNum(raw) {
  if (raw == null) return null;
  let s = String(raw).trim();
  if (!s || !/\d/.test(s)) return null;
  s = s.replace(/\s+/g, "").replace(/g\b|g$/i, "").replace(/kcal|kj/gi, "").replace(/,-$/, "");
  if (s.includes(",") && s.includes(".")) {
    if (s.lastIndexOf(",") > s.lastIndexOf(".")) { s = s.replace(/\./g, "").replace(",", "."); }
    else s = s.replace(/,/g, "");
  } else if (s.includes(",")) {
    s = s.replace(/\./g, "").replace(",", ".");
  } else if (s.includes(".")) {
    const parts = s.split(".");
    if (!(parts.length === 2 && parts[1].length <= 2)) s = s.replace(/\./g, "");
  }
  const n = parseFloat(s);
  return isFinite(n) ? n : null;
}

function parseDateCell(raw) {
  const s = String(raw).trim().split(/\s+/)[0];
  const parts = s.split(/[/.\-]/).map(p => parseInt(p, 10)).filter(n => !isNaN(n));
  if (parts.length < 2 || parts.length > 3) return null;
  let d, mo, y;
  if (parts.length === 3) {
    if (/^\d{4}/.test(s)) { y = parts[0]; mo = parts[1]; d = parts[2]; }
    else if (DATE_DDMM) { d = parts[0]; mo = parts[1]; y = parts[2]; }
    else { mo = parts[0]; d = parts[1]; y = parts[2]; }
    if (y < 100) y += 2000;
  } else {
    if (DATE_DDMM) { d = parts[0]; mo = parts[1]; } else { mo = parts[0]; d = parts[1]; }
    y = new Date().getFullYear();
  }
  if (d < 1 || d > 31 || mo < 1 || mo > 12) return null;
  return { d, mo, y };
}

function sameDay(a) {
  const n = new Date();
  if (!a) return false;
  return a.d === n.getDate() && a.mo === n.getMonth() + 1 && a.y === n.getFullYear();
}

function fmt(n) {
  if (n == null) return "0";
  const abs = Math.round(Math.abs(n) * 100) / 100;
  const int = Math.floor(abs);
  const cents = Math.round((abs - int) * 100);
  const intStr = String(int).replace(/\B(?=(\d{3})+(?!\d))/g, ".");
  return cents > 0 ? `${intStr},${String(cents).padStart(2, "0")}` : intStr;
}

function truncate(s, n) { return s.length > n ? s.slice(0, n - 1) + "…" : s; }

// Render "<big number> <unit>" on one line, unit styled smaller beside the digits.
function unitBeside(parent, numText, unitText, numSize, center, accent) {
  const row = parent.addStack();
  row.layoutHorizontally();
  row.centerAlignContent();
  if (center) row.addSpacer();
  const num = row.addText(numText);
  num.font = Font.heavyRoundedSystemFont(numSize);
  num.textColor = MAIN_C;
  if (unitText) {
    row.addSpacer(5);
    const uni = row.addText(unitText);
    uni.font = Font.semiboldSystemFont(Math.max(9, Math.round(numSize * 0.4)));
    uni.textColor = accent;
  }
  if (center) row.addSpacer();
  return row;
}

async function fetchData() {
  const rows = csvToRows(await loadCsv());
  if (rows.length === 0) throw new Error("Ingen rækker i arket");
  let header = null, data = rows;
  if (HAS_HEADER) { header = rows[0].map(c => String(c).trim().toLowerCase()); data = rows.slice(1); }

  const find = rx => header ? header.findIndex(h => rx.test(h)) : -1;
  const cols = { ...FALLBACK };
  if (header) {
    const di = find(/dato|date|dag|tidspunkt|timestamp|time/);
    const ki = find(/\bcal\b|kcal|calories|kalorier|energi/);
    const pi = find(/protein/);
    const ci = find(/\bcarbs?\b|carbohydrate|kulhydrat|karbohydrat/);
    const fi = find(/fedt|\bfat\b/);
    const xi = find(/product|produkt|beskriv|note|måltid|maltid|meal|food|description|tekst|name/);
    if (di >= 0) cols.date = di;
    if (ki >= 0) cols.kcal = ki;
    if (pi >= 0) cols.protein = pi;
    if (ci >= 0) cols.carbs = ci;
    if (fi >= 0) cols.fat = fi;
    if (xi >= 0) cols.desc = xi;
  }

  const now = new Date();
  const parsed = [];
  for (const r of data) {
    const kcal = parseNum(r[cols.kcal]);
    if (kcal == null) continue;
    parsed.push({
      pd: parseDateCell(r[cols.date]),
      kcal,
      p: parseNum(r[cols.protein]) || 0,
      c: parseNum(r[cols.carbs]) || 0,
      f: parseNum(r[cols.fat]) || 0,
      desc: cols.desc >= 0 ? String(r[cols.desc] || "").trim() : "",
    });
  }

  const agg = list => list.reduce((a, x) => ({ kcal: a.kcal + x.kcal, p: a.p + x.p, c: a.c + x.c, f: a.f + x.f, meals: a.meals + 1 }),
    { kcal: 0, p: 0, c: 0, f: 0, meals: 0 });

  const todayList = parsed.filter(x => x.pd && sameDay(x.pd));
  const monthList = parsed.filter(x => x.pd && x.pd.y === now.getFullYear() && x.pd.mo === now.getMonth() + 1);
  const today = agg(todayList);
  const month = agg(monthList);
  const todayRows = todayList.slice(0, 6).map(x => ({ desc: x.desc, kcal: x.kcal }));
  return { today, month, todayRows, hasDesc: cols.desc >= 0 };
}

async function compose(data) {
  const w = new ListWidget();
  w.setPadding(14, 16, 14, 16);
  const fam = config.widgetFamily || "medium";

  if (fam === "accessoryCircular" || fam === "accessoryRectangular" || fam === "accessoryInline") {
    return composeAccessory(data, fam);
  }

  if (TRANSPARENT) {
    const pos = (args.widgetParameter || "middle").toLowerCase();
    const file = `transparent-${fam}${pos ? "-" + pos : ""}.png`;
    try {
      const img = Image.fromFile(scriptDir() + file);
      if (img) w.backgroundImage = img;
    } catch (e) { /* fall through */ }
  }
  if (!w.backgroundImage) {
    const g = new LinearGradient();
    g.locations = [0, 1];
    g.colors = [new Color("#1a1410", 0.9), new Color("#0c0906", 0.94)];
    w.backgroundGradient = g;
  }

  const now = new Date();
  const kcal = data.today.kcal;
  const kcalStr = fmt(kcal);
  const mainStack = w.addStack();
  mainStack.layoutVertically();

  const macroRow = (stack) => {
    const row = stack.addStack();
    row.layoutHorizontally();
    const items = [
      { label: "PROTEIN", v: fmt(data.today.p), color: P_C },
      { label: "CARBS", v: fmt(data.today.c), color: C_C },
      { label: "FAT", v: fmt(data.today.f), color: F_C },
    ];
    for (const it of items) {
      row.addSpacer();
      const col = row.addStack();
      col.layoutVertically();
      const v = col.addText(it.v + " g");
      v.font = Font.semiboldSystemFont(13);
      v.textColor = it.color;
      v.centerAlignText();
      const l = col.addText(it.label);
      l.font = Font.mediumSystemFont(8);
      l.textColor = MUTED_C;
      l.centerAlignText();
      row.addSpacer();
    }
  };

  if (fam === "small") {
    mainStack.addSpacer();
    unitBeside(mainStack, kcalStr, "kcal", 26, false, ACCENT_C);
    const l = mainStack.addText("i dag");
    l.font = Font.mediumSystemFont(9);
    l.textColor = ACCENT_C;
    const m = mainStack.addText(`P ${fmt(data.today.p)} · C ${fmt(data.today.c)} · F ${fmt(data.today.f)}`);
    m.font = Font.regularSystemFont(8);
    m.textColor = MUTED_C;
    mainStack.addSpacer();
  } else if (fam === "medium") {
    const d = mainStack.addText(`${WEEKDAYS[now.getDay()]} · ${now.getDate()}. ${MONTHS[now.getMonth()]}`.toUpperCase());
    d.font = Font.mediumSystemFont(10);
    d.textColor = MUTED_C;
    mainStack.addSpacer(4);
    const body = mainStack.addStack();
    body.layoutHorizontally();
    body.addSpacer();
    const left = body.addStack();
    left.layoutVertically();
    unitBeside(left, kcalStr, "kcal", 34, false, ACCENT_C);
    const l = left.addText("i dag");
    l.font = Font.mediumSystemFont(10);
    l.textColor = ACCENT_C;
    body.addSpacer();
    const right = body.addStack();
    right.layoutVertically();
    right.addSpacer();
    macroRow(right);
    right.addSpacer();
    body.addSpacer();
    mainStack.addSpacer();
  } else { // large (+extraLarge falls here)
    const head = mainStack.addStack();
    head.layoutHorizontally();
    const d = head.addText(`${WEEKDAYS[now.getDay()]} · ${now.getDate()}. ${MONTHS[now.getMonth()]}`);
    d.font = Font.mediumSystemFont(13);
    d.textColor = MUTED_C;
    head.addSpacer();
    const mo = head.addText(`${MONTHS[now.getMonth()]}: ${fmt(data.month.kcal)} kcal`);
    mo.font = Font.mediumSystemFont(11);
    mo.textColor = MUTED_C;
    mainStack.addSpacer(8);
    unitBeside(mainStack, kcalStr, "kcal", 42, false, ACCENT_C);
    const l = mainStack.addText("i dag");
    l.font = Font.mediumSystemFont(12);
    l.textColor = ACCENT_C;
    mainStack.addSpacer(10);
    macroRow(mainStack);
    mainStack.addSpacer(8);
    if (data.todayRows.length > 0) {
      for (const r of data.todayRows.slice(0, 4)) {
        const rr = mainStack.addStack();
        rr.layoutHorizontally();
        const dd = rr.addText(truncate(r.hasDesc ? r.desc : "Måltid", 26));
        dd.font = Font.regularSystemFont(12);
        dd.textColor = MUTED_C;
        dd.lineLimit = 1;
        rr.addSpacer();
        const aa = rr.addText(`${fmt(r.kcal)} kcal`);
        aa.font = Font.semiboldSystemFont(12);
        aa.textColor = MAIN_C;
        mainStack.addSpacer(5);
      }
    } else {
      const e = mainStack.addText("Ingen måltider logget endnu");
      e.font = Font.regularSystemFont(12);
      e.textColor = MUTED_C;
    }
    mainStack.addSpacer();
  }

  w.refreshAfterDate = new Date(Date.now() + REFRESH_MINUTES * 60 * 1000);
  return w;
}

function composeAccessory(data, fam) {
  const w = new ListWidget();
  const now = new Date();
  const kcalStr = fmt(data.today.kcal);
  if (fam === "accessoryCircular") {
    const size = kcalStr.length <= 4 ? 21 : kcalStr.length <= 6 ? 17 : 13;
    const st = w.addStack();
    st.layoutVertically();
    st.addSpacer();
    const t = st.addText(kcalStr);
    t.font = Font.heavyRoundedSystemFont(size);
    t.textColor = MAIN_C;
    t.centerAlignText();
    const u = st.addText("kcal");
    u.font = Font.mediumSystemFont(8);
    u.textColor = ACCENT_C;
    u.centerAlignText();
    st.addSpacer();
  } else if (fam === "accessoryRectangular") {
    const l1 = w.addText(`${kcalStr} kcal`);
    l1.font = Font.semiboldSystemFont(16);
    l1.textColor = MAIN_C;
    l1.lineLimit = 1;
    const l2 = w.addText(`P ${fmt(data.today.p)} · C ${fmt(data.today.c)} · F ${fmt(data.today.f)}`);
    l2.font = Font.regularSystemFont(11);
    l2.textColor = ACCENT_C;
    l2.lineLimit = 1;
    const l3 = w.addText(`${now.getDate()}. ${MONTHS[now.getMonth()]}`);
    l3.font = Font.regularSystemFont(9);
    l3.textColor = MUTED_C;
    l3.lineLimit = 1;
  } else {
    const t = w.addText(`🔥  ${kcalStr} kcal · P ${fmt(data.today.p)} C ${fmt(data.today.c)} F ${fmt(data.today.f)}`);
    t.font = Font.mediumSystemFont(12);
    t.textColor = MAIN_C;
    t.lineLimit = 1;
  }
  w.refreshAfterDate = new Date(Date.now() + REFRESH_MINUTES * 60 * 1000);
  return w;
}

async function run() {
  try {
    const w = await compose(await fetchData());
    Script.setWidget(w);
  } catch (e) {
    const w = new ListWidget();
    w.setPadding(12, 14, 12, 14);
    w.backgroundColor = new Color("#120d08");
    const t = w.addText("Kunne ikke hente data");
    t.font = Font.mediumSystemFont(12);
    t.textColor = Color.red();
    const s = w.addText(String(e && e.message || e));
    s.font = Font.regularSystemFont(9);
    s.textColor = new Color("#94a3b8");
    Script.setWidget(w);
  }
  Script.complete();
}
run();
