// WeightTrack — transparent Scriptable widget for body weight (kg)
// Shows your latest weight, the change since the previous weigh-in, a 7-day
// change, a mini trend line and recent entries.
//
// SETUP:
//  1) Save this file into "iCloud Drive/Scriptable".
//  2) Add a Scriptable widget -> choose "WeightTrack". Optional Parameter =
//     position for transparency ("top"/"middle"/"bottom", small: "top-left"...).
//  3) Transparency reuses the transparent-*.png files generated by SpendToday_BG.
//
// Data comes from the Weight Tracker service:
//    GET /weight-history -> [{"date":"2026-09-12","weight":84.2}, ...]
// Log a weight by running a Shortcut that POSTs to /weight, or set
// TAP_SHORTCUT below so tapping the widget opens that Shortcut.

// ---------- CONFIG ----------
const API_URL = "PASTE_YOUR_WEIGHT_API_URL_HERE";
const REFRESH_MINUTES = 15;        // widget refresh cadence (iOS decides the exact time)
const TRANSPARENT = true;
const TAP_SHORTCUT = ""; // optional: name of an iOS Shortcut to run when the widget is tapped
const GOAL_KG = null;              // e.g. 80 for a goal line (null = hide)
const TREND_DAYS = 14;             // how many entries the trend line covers
// ---------- END CONFIG ----------

const MONTHS = ["januar", "februar", "marts", "april", "maj", "juni", "juli", "august", "september", "oktober", "november", "december"];
const ACCENT_C = new Color("#2dd4bf");   // teal — weight accent
const MAIN_C = new Color("#ffffff");
const MUTED_C = new Color("#9ca3af");
const DOWN_C = new Color("#34d399");     // losing weight
const UP_C = new Color("#fbbf24");       // gaining weight

function scriptDir() {
  const fm = FileManager.iCloud();
  const p = module.filename;
  return p ? p.replace(/[^/]*$/, "") : fm.documentsDirectory();
}

function parseNum(raw) {
  if (raw == null) return null;
  let s = String(raw).trim();
  if (!s || !/\d/.test(s)) return null;
  s = s.replace(/\s+/g, "").replace(/kg/gi, "").replace(/,-$/, "");
  s = s.replace(/,/g, ".");
  const n = parseFloat(s);
  return isFinite(n) ? n : null;
}

function parseDate(raw) {
  const s = String(raw).trim().split(/\s+/)[0];
  const parts = s.split(/[/.\-]/).map(p => parseInt(p, 10)).filter(n => !isNaN(n));
  if (parts.length !== 3) return null;
  let y, mo, d;
  if (/^\d{4}/.test(s)) { y = parts[0]; mo = parts[1]; d = parts[2]; }
  else { d = parts[0]; mo = parts[1]; y = parts[2]; }
  if (y < 100) y += 2000;
  if (d < 1 || d > 31 || mo < 1 || mo > 12) return null;
  return { d, mo, y, key: `${y}-${String(mo).padStart(2, "0")}-${String(d).padStart(2, "0")}` };
}

function fmt(n) {
  if (n == null) return "0";
  const abs = Math.round(Math.abs(n) * 100) / 100;
  const int = Math.floor(abs);
  const cents = Math.round((abs - int) * 100);
  const intStr = String(int).replace(/\B(?=(\d{3})+(?!\d))/g, ".");
  return cents > 0 ? `${intStr},${String(cents).padStart(2, "0")}` : intStr;
}

function fmtKg(n) {
  if (n == null) return "0";
  const r = Math.round(Math.abs(n) * 10) / 10;
  const whole = Math.floor(r);
  const tenth = Math.round((r - whole) * 10);
  const intStr = String(whole).replace(/\B(?=(\d{3})+(?!\d))/g, ".");
  return tenth > 0 ? `${intStr},${tenth}` : intStr;
}

function deltaText(d) {
  if (d == null) return "—";
  if (Math.round(d * 10) === 0) return "± 0 kg";
  return (d > 0 ? "+" : "−") + fmtKg(Math.abs(d)) + " kg";
}

function deltaColor(d) {
  if (d == null || Math.round(d * 100) === 0) return MUTED_C;
  return d > 0 ? UP_C : DOWN_C;
}

function dayName(pd) { return pd ? `${pd.d}. ${MONTHS[pd.mo - 1]}` : ""; }

// Render "<big number> <unit>" on one line, unit styled smaller beside the digits.
function unitBeside(parent, numText, unitText, numSize, center, accent) {
  const row = parent.addStack();
  row.layoutHorizontally();
  row.centerAlignContent();
  if (center) row.addSpacer();
  const num = row.addText(numText);
  num.font = Font.heavyRoundedSystemFont(numSize);
  num.textColor = MAIN_C;
  if (unitText) {
    row.addSpacer(5);
    const uni = row.addText(unitText);
    uni.font = Font.semiboldSystemFont(Math.max(9, Math.round(numSize * 0.4)));
    uni.textColor = accent;
  }
  if (center) row.addSpacer();
  return row;
}

function sparkline(values, width, height, color) {
  if (!values || values.length < 2) return null;
  try {
    const ctx = new DrawContext();
    ctx.size = new Size(width * 2, height * 2);
    ctx.opaque = false;
    ctx.respectScreenScale = true;
    const min = Math.min.apply(null, values);
    const max = Math.max.apply(null, values);
    const span = (max - min) || 1;
    const pad = 8;
    const sx = i => pad + (i * (ctx.size.width - 2 * pad)) / (values.length - 1);
    const sy = v => pad + ((max - v) / span) * (ctx.size.height - 2 * pad);
    const path = new Path();
    values.forEach((v, i) => {
      const pt = new Point(sx(i), sy(v));
      if (i === 0) path.move(pt); else path.addLine(pt);
    });
    ctx.addPath(path);
    ctx.setStrokeColor(color);
    ctx.setLineWidth(4);
    ctx.strokePath();
    ctx.setFillColor(color);
    const lx = sx(values.length - 1), ly = sy(values[values.length - 1]);
    ctx.fillEllipse(new Rect(lx - 6, ly - 6, 12, 12));
    return ctx.getImage();
  } catch (e) {
    return null;
  }
}

async function fetchData() {
  const req = new Request(API_URL);
  req.timeoutInterval = 15;
  const raw = await req.loadJSON();
  if (!Array.isArray(raw)) throw new Error("Uventet svar fra API'et");

  const entries = [];
  for (const e of raw) {
    const pd = parseDate(e && e.date);
    const w = parseNum(e && e.weight);
    if (pd && w != null) entries.push({ pd, iso: pd.key, w });
  }
  entries.sort((a, b) => (a.iso < b.iso ? -1 : a.iso > b.iso ? 1 : 0));
  if (entries.length === 0) return { empty: true, count: 0, entries: [] };

  const latest = entries[entries.length - 1];
  const previous = entries.length > 1 ? entries[entries.length - 2] : null;
  const first = entries[0];
  const deltaPrev = previous ? latest.w - previous.w : null;

  // closest entry at least ~7 days before the latest one
  const target = new Date(latest.pd.y, latest.pd.mo - 1, latest.pd.d);
  target.setDate(target.getDate() - 7);
  const targetKey = `${target.getFullYear()}-${String(target.getMonth() + 1).padStart(2, "0")}-${String(target.getDate()).padStart(2, "0")}`;
  let weekAgo = null;
  for (const e of entries) if (e.iso <= targetKey) weekAgo = e;
  const delta7 = weekAgo ? latest.w - weekAgo.w : null;

  const recent = entries.slice(-TREND_DAYS);
  const values = recent.map(e => e.w);
  return {
    empty: false,
    count: entries.length,
    latest,
    previous,
    first,
    deltaPrev,
    delta7,
    goal: GOAL_KG,
    toGoal: GOAL_KG != null ? latest.w - GOAL_KG : null,
    min: Math.min.apply(null, values),
    max: Math.max.apply(null, values),
    values,
    recent: entries.slice(-4).reverse(),
  };
}

// Tap action: widgets can't run code on tap, but they can open a URL -- this
// makes a tap launch the configured iOS Shortcut (here: a weight logger).
function applyTapShortcut(w) {
  if (TAP_SHORTCUT) w.url = "shortcuts://run-shortcut?name=" + encodeURIComponent(TAP_SHORTCUT);
}

async function compose(data) {
  const w = new ListWidget();
  w.setPadding(14, 16, 14, 16);
  const fam = config.widgetFamily || "medium";

  if (fam === "accessoryCircular" || fam === "accessoryRectangular" || fam === "accessoryInline") {
    return composeAccessory(data, fam);
  }

  if (TRANSPARENT) {
    const pos = (args.widgetParameter || "middle").toLowerCase();
    const file = `transparent-${fam}${pos ? "-" + pos : ""}.png`;
    try {
      const img = Image.fromFile(scriptDir() + file);
      if (img) w.backgroundImage = img;
    } catch (e) { /* fall through */ }
  }
  if (!w.backgroundImage) {
    const g = new LinearGradient();
    g.locations = [0, 1];
    g.colors = [new Color("#0b1416", 0.9), new Color("#050c0d", 0.94)];
    w.backgroundGradient = g;
  }

  const mainStack = w.addStack();
  mainStack.layoutVertically();

  if (data.empty) {
    mainStack.addSpacer();
    const e = mainStack.addText("Ingen vægt logget endnu");
    e.font = Font.mediumSystemFont(13);
    e.textColor = MUTED_C;
    e.centerAlignText();
    mainStack.addSpacer();
    applyTapShortcut(w);
    w.refreshAfterDate = new Date(Date.now() + REFRESH_MINUTES * 60 * 1000);
    return w;
  }

  const latest = data.latest;
  const valueStr = fmtKg(latest.w);
  const deltaLabel = data.previous ? `siden ${dayName(data.previous.pd)}: ${deltaText(data.deltaPrev)}` : "første vejning";

  const statRow = (stack, items) => {
    const row = stack.addStack();
    row.layoutHorizontally();
    for (const it of items) {
      row.addSpacer();
      const col = row.addStack();
      col.layoutVertically();
      const v = col.addText(it.value);
      v.font = Font.semiboldSystemFont(13);
      v.textColor = it.color || MAIN_C;
      v.centerAlignText();
      const l = col.addText(it.label);
      l.font = Font.mediumSystemFont(8);
      l.textColor = MUTED_C;
      l.centerAlignText();
      row.addSpacer();
    }
  };

  if (fam === "small") {
    mainStack.addSpacer();
    unitBeside(mainStack, valueStr, "kg", 30, false, ACCENT_C);
    const d = mainStack.addText(deltaText(data.deltaPrev));
    d.font = Font.mediumSystemFont(10);
    d.textColor = deltaColor(data.deltaPrev);
    const t = mainStack.addText(latest.pd ? `${latest.pd.d}. ${MONTHS[latest.pd.mo - 1]}` : "");
    t.font = Font.regularSystemFont(8);
    t.textColor = MUTED_C;
    mainStack.addSpacer();
  } else if (fam === "medium") {
    const head = mainStack.addText("VÆGT");
    head.font = Font.mediumSystemFont(10);
    head.textColor = MUTED_C;
    mainStack.addSpacer(4);
    const body = mainStack.addStack();
    body.layoutHorizontally();
    body.addSpacer();
    const left = body.addStack();
    left.layoutVertically();
    unitBeside(left, valueStr, "kg", 36, false, ACCENT_C);
    const l = left.addText(latest.pd ? `${latest.pd.d}. ${MONTHS[latest.pd.mo - 1]}` : "");
    l.font = Font.mediumSystemFont(10);
    l.textColor = ACCENT_C;
    body.addSpacer();
    const right = body.addStack();
    right.layoutVertically();
    right.addSpacer();
    const d1 = right.addText(deltaText(data.deltaPrev) + "  siden sidst");
    d1.font = Font.semiboldSystemFont(11);
    d1.textColor = deltaColor(data.deltaPrev);
    const d2 = right.addText(data.delta7 != null ? `${deltaText(data.delta7)}  7 dage` : "—");
    d2.font = Font.regularSystemFont(11);
    d2.textColor = data.delta7 != null ? deltaColor(data.delta7) : MUTED_C;
    if (data.toGoal != null) {
      const g = right.addText(`mål ${fmt(data.goal)} kg · ${deltaText(data.toGoal)}`);
      g.font = Font.regularSystemFont(10);
      g.textColor = MUTED_C;
    }
    right.addSpacer();
    body.addSpacer();
    mainStack.addSpacer();
  } else { // large (+extraLarge)
    const head = mainStack.addStack();
    head.layoutHorizontally();
    const d = head.addText(dayName(latest.pd));
    d.font = Font.mediumSystemFont(13);
    d.textColor = MUTED_C;
    head.addSpacer();
    const c = head.addText(`${data.count} vejninger`);
    c.font = Font.mediumSystemFont(11);
    c.textColor = MUTED_C;
    mainStack.addSpacer(6);
    unitBeside(mainStack, valueStr, "kg", 44, false, ACCENT_C);
    const l = mainStack.addText(latest.pd ? `${latest.pd.d}. ${MONTHS[latest.pd.mo - 1]} · ${deltaLabel}` : "");
    l.font = Font.mediumSystemFont(11);
    l.textColor = MUTED_C;
    mainStack.addSpacer(8);
    statRow(mainStack, [
      { label: "SIDEN SIDST", value: deltaText(data.deltaPrev), color: deltaColor(data.deltaPrev) },
      { label: "7 DAGE", value: deltaText(data.delta7), color: deltaColor(data.delta7) },
      { label: "FRA START", value: deltaText(latest.w - data.first.w), color: deltaColor(latest.w - data.first.w) },
      data.toGoal != null
        ? { label: `MÅL ${fmtKg(data.goal)}`, value: deltaText(data.toGoal), color: ACCENT_C }
        : { label: "MIN / MAX", value: `${fmtKg(data.min)} / ${fmtKg(data.max)}`, color: ACCENT_C },
    ]);
    mainStack.addSpacer(8);
    const img = sparkline(data.values, 150, 34, ACCENT_C);
    if (img) {
      const el = mainStack.addImage(img);
      el.imageSize = new Size(150, 34);
      el.centerAlignImage();
    }
    mainStack.addSpacer(8);
    for (const r of data.recent) {
      const rr = mainStack.addStack();
      rr.layoutHorizontally();
      const dd = rr.addText(dayName(r.pd));
      dd.font = Font.regularSystemFont(12);
      dd.textColor = MUTED_C;
      dd.lineLimit = 1;
      rr.addSpacer();
      const aa = rr.addText(`${fmtKg(r.w)} kg`);
      aa.font = Font.semiboldSystemFont(12);
      aa.textColor = MAIN_C;
      mainStack.addSpacer(4);
    }
    mainStack.addSpacer();
  }

  applyTapShortcut(w);
  w.refreshAfterDate = new Date(Date.now() + REFRESH_MINUTES * 60 * 1000);
  return w;
}

function composeAccessory(data, fam) {
  const w = new ListWidget();
  if (data.empty) {
    const t = w.addText(fam === "accessoryInline" ? "Ingen vægt endnu" : "—");
    t.font = Font.mediumSystemFont(12);
    t.textColor = MUTED_C;
    return w;
  }
  const valueStr = fmtKg(data.latest.w);
  const dayStr = data.latest.pd ? `${data.latest.pd.d}. ${MONTHS[data.latest.pd.mo - 1]}` : "";
  if (fam === "accessoryCircular") {
    const size = valueStr.length <= 4 ? 22 : valueStr.length <= 6 ? 18 : 14;
    const st = w.addStack();
    st.layoutVertically();
    st.addSpacer();
    const t = st.addText(valueStr);
    t.font = Font.heavyRoundedSystemFont(size);
    t.textColor = MAIN_C;
    t.centerAlignText();
    const u = st.addText("kg");
    u.font = Font.mediumSystemFont(8);
    u.textColor = ACCENT_C;
    u.centerAlignText();
    st.addSpacer();
  } else if (fam === "accessoryRectangular") {
    const l1 = w.addText(`${valueStr} kg   ${deltaText(data.deltaPrev)}`);
    l1.font = Font.semiboldSystemFont(16);
    l1.textColor = MAIN_C;
    l1.lineLimit = 1;
    const l2 = w.addText(dayStr + (data.count ? ` · ${data.count} vejninger` : ""));
    l2.font = Font.regularSystemFont(11);
    l2.textColor = ACCENT_C;
    l2.lineLimit = 1;
    const l3 = w.addText(data.delta7 != null ? `7 dage: ${deltaText(data.delta7)}` : "Ingen 7-dages historik");
    l3.font = Font.regularSystemFont(9);
    l3.textColor = MUTED_C;
    l3.lineLimit = 1;
  } else {
    const t = w.addText(`⚖️ ${valueStr} kg · ${deltaText(data.deltaPrev)}`);
    t.font = Font.mediumSystemFont(12);
    t.textColor = MAIN_C;
    t.lineLimit = 1;
  }
  applyTapShortcut(w);
  w.refreshAfterDate = new Date(Date.now() + REFRESH_MINUTES * 60 * 1000);
  return w;
}

async function run() {
  try {
    const w = await compose(await fetchData());
    Script.setWidget(w);
  } catch (e) {
    const w = new ListWidget();
    w.setPadding(12, 14, 12, 14);
    w.backgroundColor = new Color("#07100f");
    const t = w.addText("Kunne ikke hente vægt");
    t.font = Font.mediumSystemFont(12);
    t.textColor = Color.red();
    const s = w.addText(String((e && e.message) || e));
    s.font = Font.regularSystemFont(9);
    s.textColor = new Color("#94a3b8");
    Script.setWidget(w);
  }
  Script.complete();
}
run();
